### ISSUE TITLE
Would this work with vue3 and Vite

### ISSUE THREAD

**Issue by mingsterism** [siegerts/vue-component-library-template#14]
Hi, 
I'm trying to convert this to use Vue3 and package bundler vite.
Would it work? 

Thanks

**Comment by siegerts** [comment]
Hi @mingsterism ,

Since this is coupled with VuePress, you'll need to adjust/accommodate for the the pre-release version https://github.com/vuepress/vuepress-next. Regarding Vue3, the migration guide is probably the best place to identify what needs to be changed.

https://v3.vuejs.org/guide/migration/introduction.html#overview
